apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opsera-chenaiexpo-dev

resources:
- ../../base

patches:
- path: deployment-patch.yaml

commonLabels:
  environment: dev
  tenant: opsera
